### PR TITLE
Modularize build

### PR DESCRIPTION
**Pull request by rpavlik**
This would fix the packaging difficulties, while keeping the CMake code for the various external dependencies fairly split up and modular.  A good rule of thumb to keep in mind: If a directory includes external/vendored code (that might already be packaged) or a binary file (especially without complete source), that directory is likely to be entirely removed from distribution source packaging.

There are a few things here you might not want (specifically the fixing of mpir bundled binaries, and the option to build server: if you don't want that, then remove the server entirely - if it cannot be built it will certainly bit-rot.) - feel free to `git cherry-pick` or let me know which commits to drop.

What happened to CI building pull requests?

### CODE REVIEW

**Comment by alemuntoni** [comment]
Cool, thanks @rpavlik! I'll take a deep look to this tomorrow :) I can drop #846 then!
About meshlabserver, I'll move it to the unsupported directory soon (qmake still builds it, therefore I need to do some passes also on that).
What are you referring to about CI building pull requests? We are keeping both cmake and qmake atthe moment, and in cmake we have both builds using floats and double , therefore there are 9 checks in total.

**Comment by rpavlik** [comment]
Ah, now I see the checks. I didn't see it running any checks before.

**Comment by alemuntoni** [comment]
PR is fine to me, thanks again @rpavlik, and sorry for all the extra work! 
I'll ping you everytime there will be a big change in the build system!

**Comment by rpavlik** [comment]
great, thank you so much!

**Pull request merged**
