### PR TITLE
Document filters_unsharp tooltips

### PR DESCRIPTION
**Pull request by jmespadero**
Done
Add some bibtex references to tooltips in filters. No code changes.

Example:
image

### CODE REVIEW

**Comment by cignoni** [comment]
Thanks!
Having the doi everywhere would be great!!!

**Comment by jmespadero** [comment]
Give me a couple of days and I will recopilate as many as I can.

**Comment by jmespadero** [comment]
I have finished the documentation of the filters in filter_unsharp. Lots of links to papers and also some links to basic concepts that I have had to explain sometimes:

* [Quality per vertex](https://stackoverflow.com/questions/58610746)
* [Faux edges](https://stackoverflow.com/questions/59393865)

I suppose that easiest way to present changes to your revision is this collage. Click to enlarge.

image

**Comment by cignoni** [comment]
Thanks for the large set of improvements!
I have only a few doubts on the link to stackoverflow explanation of faux edges... 
I would have preferred a link to the vcglib documentation, but given that such a page  do not exist 🤦‍♂️, stackoverflow probably it is a reasonable workaround...

**Comment by jmespadero** [comment]
> one day someone will write something decent for this page http://vcglib.net/flags.html

That should be nice. The fact is that it is not easy to find a page where faux edges are described to beginners in CG, and a page to an C++ api may be not what a new user is looking for.

**Comment by alemuntoni** [comment]
Thank you @jmespadero!!

**Pull request merged**
