### PR TITLE
filter_csg: Add ifdef to permit building against gmp

### PR DESCRIPTION
**Pull request by rpavlik**
Docs mention building with GMP or MPIR, but MPIR was unconditionally included. GMP is way more common on linux systems, so worth trying to use. It seemed to work, though I ran my computer out of memory trying to test it.

### CODE REVIEW

**Comment by cignoni** [comment]
yes for linux GMP should be used. MPIR was just used as a replacement because GMP did not easily compile

**Comment by rpavlik** [comment]
awesome, thanks for the info! Do you want me to adjust the qmake build accordingly?

**Comment by rpavlik** [comment]
OK, updated to have qmake use system-wide GMP for this plugin.

**Comment by rpavlik** [comment]
Updated to fix merge conflict.

**Pull request merged**
