### PR TITLE
RFC: Port filter_qhull to reentrant libqhull version

### PR DESCRIPTION
**Pull request by StefanBruens**
This MR ports filter_qhull to use the reentrant version of Qhull. qhull_r is available since Qhull 2015.1, and the non-reentrant version is no longer built with version 2020.1.

This currently only works for a system Qhull >= 2015.1, as the bundled 2003.1 is to old.

### CODE REVIEW

**Comment by alemuntoni** [comment]
Thanks @StefanBruens. 
Before merging this, we should update the bundled version of qhull inside meshlab. 
At this point, I would bundle the last version..

**Comment by alemuntoni** [comment]
[Here](https://github.com/alemuntoni/meshlab/tree/use_reentrant_qhull) I tried to bundle a recent version of qhull, but without success. Right now I don't have much time to investigate why it does not work.
We need to have everything working on all the three platforms (it must work on ubuntu 18.04 due to [appimage requirements](https://docs.appimage.org/introduction/concepts.html#build-on-old-systems-run-on-newer-systems)). If someone could help would be really appreciated.

**Comment by alemuntoni** [comment]
Nevermind, I think I fixed it. @StefanBruens could you please take a look at [this branch](https://github.com/alemuntoni/meshlab/tree/use_reentrant_qhull)? If it convinces you, I can push it on this PR.

The only problem is that apparently Qhull 2015 (which is provided in ubuntu 18.04 and 20.04) is not compatible with Qhull 2020 (which I think will be in 22.04). 
Since the bundled version is Qhull 2020, it would be ideal to check [here](https://github.com/alemuntoni/meshlab/blob/c5b719ebfab56d7464771d3c1cd832487b78f202/src/external/qhull.cmake#L11) if the version of the target found is 2020.
However, it seems that `VERSION` is not a property of the Qhull target, therefore I don't know if there is a easy way to do this...

Therefore, the only way to build the plugin correctly on ubuntu 18.04 and 20.04 having `libqhull-dev` installed, is to disable the cmake option `ALLOW_SYSTEM_QHULL` manually.

**Comment by StefanBruens** [comment]
Probably the easiest solution is to completely drop the homegrown FindQhull.cmake and rely on Qhulls own cmake support:

`find_package(Qhull 8 COMPONENTS qhull_r)`

(Version 8.y is the soversion matching 2020.x)

**Comment by alemuntoni** [comment]
Thanks, I've done it in the last commit of my branch.
Cmake complains that I am not providing `FindQHull.cmake` (and then uses the bundled sources, as expected). 
Is that possible that the 2015 version in ubuntu 18.04 did not provide proper cmake support?

**Comment by StefanBruens** [comment]
Its probably related to the missing `extern "C"` in Qhull versions prior to 2018.3/7.3.0, see
https://github.com/qhull/qhull/commit/2681baa637474784156ff05f9dd2d138b29d7f4d#diff-d651e3d3dc64e06c89c2c54bc804a0836e41f03078383103afde684549744ec7

If you want to silence the cmake warning, use `find_package(... CONFIG)`.

**Comment by StefanBruens** [comment]
Sure

**Pull request merged**
