### PR TITLE
Snap: add meshlabserver

### PR DESCRIPTION
**Pull request by mardy**
Fixes issue #98

### CODE REVIEW

**Comment by cignoni** [comment]
Great Thanks! 
I am building it and trying to update the official package

**Comment by cignoni** [comment]
Hi, I am also trying to make the snapcraft for the next release 201703 and for that reason I did a bit of reorganization. Moreover, it also works with Ubuntu 201610 so I changed the readme accordingly. 
A couple of requests (my knowledge of snapcraft is rather scarce):
- Is it possible to limit the pull of the meshlab repository in some way? I have looked at the options of the 'dump' plugin but without success...
- Is it possible to give the `meshlabserver` command just  the original name instead of `meshlab.meshlabserver`?
- I got a warning when uploading on the ubuntustore the updated snap, but I hope to cope with it...

BTW, thanks again!

**Comment by mardy** [comment]
Hi! Here's my answers, to the best of my knowledge:

- Yes, it's certainly possible. You could try to replace the value of the `source` field with
```
source: ../..
source-type: git
```
I didn't try it, but it should work.

- Not automatically, but have a look at https://insights.ubuntu.com/2017/01/28/ubuntu-core-how-to-enable-aliases-for-your-snaps-commands/

- Which warning? Might be something important (usually a warning means that your package has to go through a manual review process, which could take a few days).

- It may be that you need to run `snapcraft clean` first, to remove any files previously marked for installation. Does that help?

**Comment by cignoni** [comment]
The warning was: 
`desktop interfaces (unity7,x11) specified without meta/gui/*.desktop. Please provide a desktop file via setup/gui/*.desktop if using snapcraft or meta/gui/*.desktop otherwise. It should reference one of the 'apps' from your snapcraft/snap.yaml. lint-snap-v2_meta_gui_desktop`

I added a desktop file for meshlabserver and redid the snap and re-uploaded but it seems that there is no way of removing a previous upload until the manual review process is ended...

**Comment by cignoni** [comment]
Update. The review process of the snap failed with the following motivation:

> Rejected by Jamie Strandboge. “desktop interfaces (unity7,x11) specified without meta/gui/*.desktop. Please provide a desktop file via setup/gui/*.desktop if using snapcraft or meta/gui/*.desktop otherwise. It should reference one of the 'apps' from your snapcraft/snap.yaml. lint-snap-v2_meta_gui_desktop
> 
> Please add a desktop file and reupload.” — Jamie Strandboge

I tried to do this (look at the snap201612 folder)

**Comment by mardy** [comment]
Please see pull request #106 :-)

**Pull request merged**
