### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by rpavlik**
The first two commits make the build system more resilient. The remaining commits disable on Linux some bundled "external" libraries that are often available from Linux distributions:

- Eigen3
- GLEW
- lib3ds
- openctm
- bzip2

Probably could be simplified more, but I'm not a qmake expert.

### CODE REVIEW

**Comment by rpavlik** [comment]
OK I pushed a new change that adds some config options. Travis now will build using the bundled libs again, since I haven't added those options to the travis config yet.

Something like this will maximally use system libs (testing on Debian Buster):

```sh
qmake CONFIG+=system_eigen3 CONFIG+=system_glew CONFIG+=system_lib3ds CONFIG+=system_openctm CONFIG+=system_bzip2 meshlab_full.pro
```

**Comment by alemuntoni** [comment]
Hi, thank you for this pull request!
Since Travis is failing now, can you update the Travis script such that qmake is called with the config system arguments you suggested (on Linux environment)?

**Comment by rpavlik** [comment]
OK, I cleaned up and squashed those commits, and fixed the issue that was breaking travis (hopefully) - I can now build either with the bundled Eigen, etc. or the system ones on my debian machine, and Travis will test both configurations.

I've also documented how to use this system-library capability in the readme file.

**Comment by rpavlik** [comment]
ok, guess I have some more tweaks to make

**Comment by rpavlik** [comment]
OK, this seems to be working now, in both modes (with/without bundled deps)

**Pull request merged**
