### PR TITLE
Added linux build example (Ubuntu 16)

### PR DESCRIPTION
**Pull request by martinruenz**
See src/README.md

### CODE REVIEW

**Comment by martinruenz** [comment]
I think this might be useful, as it took me a bit to get the compilation to work.
If this is not compiling, please check my vcglib pull-request: https://github.com/cnr-isti-vclab/vcglib/pull/13

**Comment by cignoni** [comment]
Thanks for the contribution!
Just a question, I see that you have to explicitly set in the QMAKE_FLAGS things that are already defined in the qmake pro's . Are they really necessary?

**Comment by martinruenz** [comment]
Hi,
probably not, flags that were definitely required (at least on my machine) are:
```
INCLUDEPATH+=/usr/include/eigen3
QMAKE_CXXFLAGS+=-fpermissive
CONFIG+=c++11
QMAKE_CXXFLAGS+=-std=c++11 #(not sure if both, though)
QMAKE_CXXFLAGS+=-fPIC
```
I think to add `CONFIG+=release` is helpful, as it shows how to switch debug / release build. The other flags might be redundant.

**Comment by DBobkov** [comment]
Perhaps, you could find my comment useful at [Comment](https://github.com/cnr-isti-vclab/meshlab/issues/74#issuecomment-279254296), where I give a script for Meshlab 2016.12 for Ubuntu 14.04 with gcc-4.9.

**Comment by jnweiger** [comment]
I've just done it successfully like this on Linux Mint 18.1 (Serena):
<pre>
sudo apt-get install qt5-qmake g++ qtscript5-dev libqt5xmlpatterns5-dev libqt5opengl5-dev
qmake -qt=5 -v

git clone --depth 1 git@github.com:cnr-isti-vclab/meshlab.git
git clone --depth 1 git@github.com:cnr-isti-vclab/vcglib.git -b devel

cd meshlab

QMAKE_FLAGS="-spec linux-g++ CONFIG+=release CONFIG+=qml_release CONFIG+=c++11QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive INCLUDEPATH+=/usr/include/eigen3 LIBS+=-L`pwd`/lib/linux-g++"
MAKE_FLAGS="-j1"

cd src/external
qmake -qt=5 external.pro $QMAKE_FLAGS && make $MAKE_FLAGS
cd ../common
qmake -qt=5 common.pro $QMAKE_FLAGS && make $MAKE_FLAGS
cd ..
qmake -qt=5 meshlab_mini.pro $QMAKE_FLAGS && make $MAKE_FLAGS
qmake -qt=5 meshlab_full.pro $QMAKE_FLAGS && make $MAKE_FLAGS

# ./distrib/meshlab

</pre>
Thanks for the helpful instructions!

Not sure why the QMAKE_FLAGS=() syntax did not work with my bash.

**Comment by BETLOG** [comment]
Confirming that @jnweiger script above works for 
Meshlab 2016.12
on
Ubuntu 16.04.2 LTS
Linux betlogbrick 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 
Many thanks. The repo version differs enough to make following instructions/tutorials difficult, and for a noobie at compiler wrangling this took far too long to get working. You just made it much easier.

**Comment by nh2** [comment]
So what's up here, why does the released 2016.12 not compile on pretty much any Linux distribution?

In `make` I'm getting

```
g++ -c -m64 -pipe -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I. -Issynth -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtScript -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o VoxelStepper.o ssynth/SyntopiaCore/GLEngine/Raytracer/VoxelStepper.cpp
ssynth/SyntopiaCore/GLEngine/Raytracer/VoxelStepper.cpp:125:7: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
       if (!found) return nullptr;
       ^
ssynth/SyntopiaCore/GLEngine/Raytracer/VoxelStepper.cpp: In member function ‘QList<SyntopiaCore::GLEngine::Object3D*>* SyntopiaCore::GLEngine::VoxelStepper::setupRay(SyntopiaCore::Math::Vector3f, SyntopiaCore::Math::Vector3f, double&)’:
ssynth/SyntopiaCore/GLEngine/Raytracer/VoxelStepper.cpp:125:26: error: ‘nullptr’ was not declared in this scope
       if (!found) return nullptr;
                          ^
```

and it seems that simply `-std=c++11` is missing in the compiler invocation.

**Comment by mdeff** [comment]
For reference, there are Archlinux PKGBUILD for [2016.12](https://aur.archlinux.org/packages/meshlab/) and the [latest git](https://aur.archlinux.org/packages/meshlab-git/). They worked for me (and many people it seems). They do however apply some patches.

**Comment by luckygoodlily** [comment]
Thank you for your contribution!
I have one error in this code,when I install this program.
Like this...
{Run Build 
Command:"C:/PROGRA~2/MIB055~1/2017/COMMUN~1/Common7/IDE/COMMOM~1/CMAKE/Ninja/ninja.exe"
"cmTC_d5510"

ninja:error:build.ninja:30:loading 'rules.ninja':
系統找不到指定的檔案。 (The system cannot find the specified file) }
I try to solve this problem, but I can't . Is there any solution?

**Comment by cielavenir** [comment]
Hopefully debuild with http://ppa.launchpad.net/zarquon42/meshlab/ubuntu/pool/main/m/meshlab/meshlab_2016.12~trusty2.tar.xz is still working

- pull debian folder from that xz
- git clone https://github.com/cnr-isti-vclab/meshlab
    - apply https://github.com/cnr-isti-vclab/meshlab/pull/349
- git clone https://github.com/cnr-isti-vclab/vcglib

then you can execute debuild -uc -us

**Pull request merged**
