### PR TITLE
CMake-based build system

### PR DESCRIPTION
**Pull request by rpavlik**
In theory this should make build setup and configuration a lot easier, letting e.g. distributions skip plugins they don't want if there is a dependency they can't use or something, etc.  (MeshLab is being removed from Debian because getting a newer, qt5-using version to build was too hard for the current maintainer, etc - https://tracker.debian.org/pkg/meshlab ) Was surprisingly easy to get these CMake scripts generated and going quickly - it's not complete yet, but a surprisingly large subset of the package works, and the only bundled dependencies being used (required) so far are jhead and vcglib.

Right now all CMakeLists.txt files besides the main one are being generated with a Python script and some Jinja2 templates: I'll remove those before it's ready to merge.

Additionally, since this is a much cleaner build with fewer things disabled, etc, a lot more warnings (many of which look like they are pointing out real bugs) show up.

### CODE REVIEW

**Comment by jmespadero** [comment]
I won't wait until this is finished to thank you for the effort you are doing to keep meshlab updated.

**Comment by simonschmeisser** [comment]
I would really appreciate having a newer release based on CMake and have it in Debian. I can try to help you wherever needed!

**Comment by jmespadero** [comment]
Hi @rpavlik 

I have created a fork of VCGlib with lots of warnings and minor bugs solved, as well as CMakeFiles.txt for directories apps/samples and apps/test. Just like the work you are doing here.

If you want to give an opportunity... just use [jmespadero/vcglib](https://github.com/jmespadero/vcglib) instead of cnr-isti-vclab/vcglib. 

Branches master and devel are equal.

**Comment by rpavlik** [comment]
@jmespadero ah, cool! I didn't have to add any files to vcglib myself to get this building, but I'll take a look when I can.

I'm at a stopping point for now here, I have all the "easy" stuff building and installing nicely, tested on Linux (in install tree and build tree). There are some plugins that are still disabled, mainly those with extra dependencies.

There are some patches in this branch that should be pulled out and merged separately since they aren't necessarily specific to using CMake.

**Comment by rpavlik** [comment]
BTW - my focus is also on building with external libraries rather than bundled versions - the cmake changes to use bundled versions optionally if the external ones can't be found shouldn't be too rough, I just can't put any more time into it at the moment.

**Comment by jmespadero** [comment]
Hi @rpavlik ,

I have compiled this branch and some filters are missing (for example, FF_VERT_SELECTION and FF_FACE_SELECTION). I have search where the problem could be, but the files `meshlabplugins/filter_func/filter_func.h` and `meshlabplugins/filter_func/filter_func.cpp` seems to be the same than original meshlab master branch.

Is it due to WIP state? Should I wait or should I investigate the cause? Can I help with this task?

**Comment by alemuntoni** [comment]
Hi @rpavlik,
thank you again also for this pull request!
It would be great to have also a cmake build system in meshlab, although we would prefer to keep qmake as default. 
Let me know if you're planning to fix the missing filters mentioned by @jmespadero! I'm not very familiar with cmake, so I can't help on fixing them :(

**Comment by rpavlik** [comment]
@jmespadero So if you look at `src/CMakeLists.txt` you'll see the same plugin lists as in the qmake `.pro` files. There are a few that are commented out, mostly because they need a dependency that I hadn't yet added to the build system (whether by finding or detecting). filter_func is one of those plugins: it needs libmuparser. Because of the manual addition of the _UNICODE define and usage of the wide-string APIs (added somewhat recently), we can't directly use system-provided muparser on Linux, and I avoided dealing with that potentially hairy problem since I don't use that plugin myself.

You're welcome to dig into the CMake files and see if you can follow the same pattern I used to make these:

- The main CMakeLists.txt file is manually edited, as is the `external.cmake` file that creates targets for using bundled libraries, but the rest are all generated by `./make-cmake.py`
- For a given directory with last component "x", if there's a `src/templates/x.cmake` file, it will use that - otherwise it will use `src/templates/CMakeLists.template.cmake` (which serves as the base template) to generate the CMakeLists.txt
  - The templates are all plain old Jinja2 templates, nothing magic. Lots of docs out there on how to modify them.
  - For best results, you do want to have cmake-format installed locally and lightly modified (see the top of make-cmake.py) so that it is applied before saving the file.
 - If you'd rather edit the CMakeLists.txt files directly for now, that's fine: just ping me or send a PR to me and I can port your changes into the templates.
 - I imagine that eventually the CMakeLists.txt-generating scripts and templates will go away, since that's not a very typical way of working with CMake - however, while the builds are all so similar it was easy to do and meant I didn't have to figure out e.g. the license headers right away :)

@alemuntoni: How do people normally use the files in plugins_experimental and plugins_unsupported? I assume some folks build them or they wouldn't be included, but I wasn't sure how to include them in the build system.

**Comment by rpavlik** [comment]
OK, I've now enabled a few more plugins:

- io_3ds
- filter_csg
- filter_func
- filter_isoparametrization
- filter_sdfgpu

This leaves only the following from plugin parity vs the qmake build of meshlab_full:

- io_ctm
- filter_qhull
- filter_ssynth

**Comment by alemuntoni** [comment]
@rpavlik plugins_experimental are plugins that have been developed but builded only by the people that developed them. They are not robust enough to be included in meshlab plugins. 
In plugins_unsupported there are old plugins not supported anymore because replaced or based on unsupported external libraries. They are there only for historical reasons. 
I'll add some readmes to explain this!
In both cases there is no need to create the cmake build :)

**Comment by rpavlik** [comment]
OK, I have all the plugins building. There's some TODOs left (and I need to put on license headers) but it's worth trying. Should work on Linux, no idea if it works on Windows or Mac.

The first few commits are all build-system-independent fixes that I'll pull into a separate PR.

**Comment by rpavlik** [comment]
OK, now all libraries you can use a system version of (if one exists in Debian). There are a few where using CMake requires you to use a system version despite a bundled one existing - from a packaging point of view this doesn't bother me much, but I'll probably poke at that next week a little bit.

**Comment by rpavlik** [comment]
Can also add plugins from experimental, etc.

image

**Comment by cignoni** [comment]
plugins in _unsupported_ and _experimental_ folders should not be compiled. Most of them are there just for historical reasons, some are plain duplicates with lesser features or even could not compile just for incompatibility with newer version of the vcglib

**Comment by rpavlik** [comment]
Would it make sense to remove them since they're in version control anyway? FWIW, many of the dependencies bundled in external are only used by plugins in those two places.

**Comment by alemuntoni** [comment]
I think also this should be rebased in order to fix the compilation of jhead in windows, fixed in #522.

**Comment by rpavlik** [comment]
ah thanks for catching that jhead makefile thing.  I've rebased this on top of my local "best" branch (cmake-base - it's master + #523 + #513 )

I have added OpenMP support (automatically enabled if available) since completing the full number of plugins.

**Comment by rpavlik** [comment]
I also added basic license headers (BSL-1.0, basically as permissive as you can get) to the build system files and took the WIP flag off accordingly: I've used the cmake-built version here a little bit and it seems OK. Would be nice if we could get a release of meshlab and vcglib soon (after merging this, if anyone is interested in merging it) so I can poke the Debian maintainer to let them know the build should be much simpler now.

**Comment by rpavlik** [comment]
And now it builds nicely on Windows - tested with both MS Visual Studio (IDE) and command line using Ninja. The "install" target will automatically run windeployqt so just set CMAKE_INSTALL_PREFIX to wherever you want your MeshLab Portable copy and build the install target.

**Comment by alemuntoni** [comment]
Great @rpavlik, thank you very much for this PR!!!

**Pull request merged**
