### PR TITLE
Allow all filetypes supported by meshlab to be opened with meshlabserver

### PR DESCRIPTION
**Pull request by feilen**
VisualSFM (and some other formats) output *.nvm, *.rd.out projects that
meshlab can easily import and use, but the logic for this never made it
into meshlabserver. I pretty much just wholesale copied/adapted the
existing code from meshlab into meshlabserver, allowing any supported
project to be imported like any other mlb file.

Before:
```
meshlabserver -p output.nvm -i output.0.ply -o export.ply
Loading Plugins:
Current Plugins Dir is: /usr/lib/x86_64-linux-gnu/meshlab/plugins
Total 249 filtering actions
Total 13 io plugins
Project /home/feilen/brutesfm-king.mkv/sfm-king.mkv0/output.nvm is not a valid 'mlp' file format. MeshLabServer application will exit.
```

Now:
```
meshlabserver -p output.nvm -i output.0.ply -o export.ply
Loading Plugins:
Total 265 filtering actions
Total 13 io plugins
MeshLab Project /home/feilen/brutesfm-king.mkv/sfm-king.mkv0/output.nvm has been loaded.
Mesh /home/feilen/brutesfm-king.mkv/sfm-king.mkv0/output.0.ply loaded has 30158 vn 0 fn
...
output mesh  /home/feilen/brutesfm-king.mkv/sfm-king.mkv0/export.ply
...
Mesh /home/feilen/brutesfm-king.mkv/sfm-king.mkv0/output.0.ply saved as /home/feilen/brutesfm-king.mkv/sfm-king.mkv0/export.ply (30158 vn 0 fn)
```

### CODE REVIEW

**Comment by alemuntoni** [comment]
Hi @feilen, thank you for the PR. Before merging it, I'll modify a few things:
- the #include alnparser.h in vcglib is horrible (our fault). I'll move the file alnparser.h inside vcglib 
- a bit of reorganization in order to minimize the code duplication between meshlab and meshlabserver

**Comment by feilen** [comment]
I agree on the deduplication. Besides what I had to comment or convert to fprintf, the routines are pretty much identical and should all be moved to common ideally.

**Comment by alemuntoni** [comment]
Input/output of projects in meshlab actually requires a more in-depth reorganization (through plugins, as it is done with the input/output of meshes). Therefore I'll merge as it is, in order to have this feature running on 2020.07. Thank you @feilen!

**Comment by feilen** [comment]
Certainly! This was just what I needed to get my workflow up and running.

**Pull request merged**
