### PR TITLE
Add global registration plugin base on OpenGR

### LINKED ISSUE #624: Plugin Point-Cloud registration (Super4PCS) using OpenGR
Dear Meshlab crew,

Would you be interested in a plugin for point-cloud registration, based on the library OpenGR ?

I have developed this some time ago, but it was hard to maintain on my side only (https://github.com/STORM-IRIT/OpenGR/tree/56eafeeba00025da395a38157364262ab313a034/demos/MeshlabPlugin).
So I disabled it recently (https://github.com/STORM-IRIT/OpenGR/commit/7f11a483b297716337c969435e0470932c3bf07c).
Would you consider adding such plugin in Meshlab directly ? I have some user requests for that (https://github.com/STORM-IRIT/OpenGR/issues/49#event-3166722856)

Cheers,
Nicolas

### PR DESCRIPTION
**Pull request by nmellado**
Code source taken from: https://github.com/STORM-IRIT/OpenGR/tree/56eafeeba00025da395a38157364262ab313a034/demos/MeshlabPlugin

The OpenGR library needs to be added as dependency to get this plugin working.

Fixes #624

### CODE REVIEW

**Comment by alemuntoni** [comment]
Great, thanks @nmellado! I'll work on this and I'll try to have it working for 2020.07 version! :)

**Comment by nmellado** [comment]
That would be amazing, thanks !

**Comment by alemuntoni** [comment]
I imported the library in meshlab and added the plugin to the qmake config of meshlab.
There were some missing template arguments that I had to add on globalregistration.cpp.
There are still two missing templates for gr::AdaptivePointFilter::Options on lines 183 and 186, and I'm not sure which types should be added there.

**Comment by nmellado** [comment]
Ok thanks a lot.
Sorry for the template stuff, this is due to some changes we had in the library in the meantime.
I'll fix it.

**Comment by alemuntoni** [comment]
great, thanks!

**Comment by nmellado** [comment]
ezgif com-video-to-gif

**Comment by alemuntoni** [comment]
Apparently there is something to fix on windows on OpenGR, I'll look into it!

**Comment by alemuntoni** [comment]
Great, thanks very much @nmellado!!

**Pull request merged**
