### PR TITLE
Install app icon in XDG hicolor icon theme

### PR DESCRIPTION
**Pull request by pinotree**
Install the icon of the application in the hicolor XDG icon theme; this way it can be properly loaded by XDG menus in the currently set XDG icon theme, without looking in the legacy pixmaps location.

As result, adapt the desktop file by removing the full path to the icon (which was already buggy for installations in prefixes different than `/usr`), so the bare icon name will be searched in the XDG icon theme as expected.

Also, remove the manual icon copying in a bundle script, as the icon is installed in the right place now.

### CODE REVIEW

**Comment by alemuntoni** [comment]
Thanks @pinotree!

@rpavlik what do you think? Is that something that breaks debian packaging?

**Comment by pinotree** [comment]
> Is that something that breaks debian packaging?

I'm not Ryan, however I'm a DD (with Debian experience), and from what I can see nothing needs changes (everything is installed directly into `debian/meshlab`, which is the only binary package).

**Comment by alemuntoni** [comment]
> > Is that something that breaks debian packaging?
> 
> I'm not Ryan, however I'm a DD (with Debian experience), and from what I can see nothing needs changes (everything is installed directly into `debian/meshlab`, which is the only binary package).

Oh ok, great! 
I asked Ryan since he is taking care of debian packaging of meshlab and I don't know all the details related to it :)

**Comment by pinotree** [comment]
> I asked Ryan since he is taking care of debian packaging of meshlab and I don't know all the details related to it :)

Oh no problem, really. I'm fine waiting for Ryan's feedback so we are all sure about it, in case.

I also realized I had forgotten a couple of changes in my initial version, and now I think to have included everything.

**Comment by rpavlik** [comment]
I think that should be fine, pretty sure I was having to apply a patch for icon install location.

**Comment by alemuntoni** [comment]
That's great!! :)
Thank you very much to both of you!

**Comment by pinotree** [comment]
>  Thank you very much to both of you!

Prego, no problem ;-)

**Pull request merged**
